# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
